### ISSUE TITLE
Clarification Needed on im_z_norm in mv_fusion

### ISSUE THREAD

**Issue by WenM1222** [noahstier/vortx#10]
I noticed that the im_z_norm value is computed as (bp_depth - 1.85) / 0.85 in the forward method.

https://github.com/noahstier/vortx/blob/c8cb0707013fc5f7eb4b941c3f354ba18c636d6a/vortx/mv_fusion.py#L36C1-L37C1

I'm a bit confused about why 1.85 and 0.85 are used for normalization. I couldn't find where it is mentioned in the paper. Can you please elaborate on these constants and the rationale behind using them?
What do 1.85 and 0.85 represent?
Are these constants specific to a certain dataset or experiment setup?
Is there a recommended way to adapt these for different use-cases?
Thank you for your time and assistance.

**Comment by noahstier** [comment]
1.85 and 0.85 are the estimated mean and standard deviation of the camera-to-voxel depth (not GT depth), computed over a random sampling of valid (within view frustum) voxels. I believe I approximated these by loading a large batch and taking mean/std of `bp_depth`.

The main factors affecting these values are scene size and camera trajectory: if the camera frequently looks from one end of the scene to the other then the average voxel depth will be high, but if the camera is frequently positioned toward the edge of the scene looking outward the average voxel depth will be low.

If you are working with a different dataset, then it might help to re-estimate these values. My guess is that it will not have a significant effect, but it might if the distribution is drastically different such as with outdoor scenes.

**Comment by WenM1222** [comment]
Thank you so much for the detailed explanation.
