### ISSUE TITLE
To generate ground truth tsdf:

### ISSUE THREAD

**Issue by BiT1022** [noahstier/vortx#2]
:~/vortx$ python tools/generate_gt.py --data_path scannet_src --save_name scannet_tsdf
0it [00:00, ?it/s]le_worker pid=23809)
  0%|          | 0/1 [00:00<?, ?it/s])
(process_with_single_worker pid=23811) read from disk
0it [00:00, ?it/s]le_worker pid=23813)
0it [00:00, ?it/s]le_worker pid=23812)
0it [00:00, ?it/s]le_worker pid=23815)
0it [00:00, ?it/s]le_worker pid=23810)
0it [00:00, ?it/s]le_worker pid=23814)
0it [00:00, ?it/s]le_worker pid=23816)
0it [00:00, ?it/s]le_worker pid=23818)
0it [00:00, ?it/s]le_worker pid=23817)
(process_with_single_worker pid=23811) scene0191_00: read frame 0/5578
0it [00:00, ?it/s]le_worker pid=23905)
0it [00:00, ?it/s]le_worker pid=24006)
0it [00:00, ?it/s]le_worker pid=23921)
0it [00:00, ?it/s]le_worker pid=24017)
0it [00:00, ?it/s]le_worker pid=23952)
0it [00:00, ?it/s]le_worker pid=23994)
(process_with_single_worker pid=23811) scene0191_00: read frame 100/5578
(process_with_single_worker pid=23811) scene0191_00: read frame 200/5578
(process_with_single_worker pid=23811) scene0191_00: read frame 300/5578
(process_with_single_worker pid=23811) scene0191_00: read frame 400/5578
(process_with_single_worker pid=23811) scene0191_00: read frame 500/5578
(process_with_single_worker pid=23811) scene0191_00: read frame 600/5578
(process_with_single_worker pid=23811) scene0191_00: read frame 700/5578
(process_with_single_worker pid=23811) scene0191_00: read frame 800/5578
(process_with_single_worker pid=23811) scene0191_00: read frame 900/5578
(process_with_single_worker pid=23811) scene0191_00: read frame 1000/5578
(process_with_single_worker pid=23811) scene0191_00: read frame 1100/5578
(process_with_single_worker pid=23811) scene0191_00: read frame 1200/5578
(process_with_single_worker pid=23811) scene0191_00: read frame 1300/5578
(process_with_single_worker pid=23811) scene0191_00: read frame 1400/5578
(process_with_single_worker pid=23811) scene0191_00: read frame 1500/5578
(process_with_single_worker pid=23811) scene0191_00: read frame 1600/5578
(process_with_single_worker pid=23811) scene0191_00: read frame 1700/5578
(process_with_single_worker pid=23811) scene0191_00: read frame 1800/5578
(process_with_single_worker pid=23811) scene0191_00: read frame 1900/5578
(process_with_single_worker pid=23811) scene0191_00: read frame 2000/5578
(process_with_single_worker pid=23811) scene0191_00: read frame 2100/5578
(process_with_single_worker pid=23811) scene0191_00: read frame 2200/5578
(process_with_single_worker pid=23811) scene0191_00: read frame 2300/5578
(process_with_single_worker pid=23811) scene0191_00: read frame 2400/5578
(process_with_single_worker pid=23811) scene0191_00: read frame 2500/5578
(process_with_single_worker pid=23811) scene0191_00: read frame 2600/5578
(process_with_single_worker pid=23811) scene0191_00: read frame 2700/5578
(process_with_single_worker pid=23811) scene0191_00: read frame 2800/5578
(process_with_single_worker pid=23811) scene0191_00: read frame 2900/5578
(process_with_single_worker pid=23811) scene0191_00: read frame 3000/5578
(process_with_single_worker pid=23811) scene0191_00: read frame 3100/5578
(process_with_single_worker pid=23811) scene0191_00: read frame 3200/5578
(process_with_single_worker pid=23811) scene0191_00: read frame 3300/5578
(process_with_single_worker pid=23811) scene0191_00: read frame 3400/5578
(process_with_single_worker pid=23811) scene0191_00: read frame 3500/5578
(process_with_single_worker pid=23811) scene0191_00: read frame 3600/5578
(process_with_single_worker pid=23811) scene0191_00: read frame 3700/5578
(process_with_single_worker pid=23811) scene0191_00: read frame 3800/5578
(process_with_single_worker pid=23811) scene0191_00: read frame 3900/5578
(process_with_single_worker pid=23811) scene0191_00: read frame 4000/5578
(process_with_single_worker pid=23811) scene0191_00: read frame 4100/5578
(process_with_single_worker pid=23811) scene0191_00: read frame 4200/5578
(process_with_single_worker pid=23811) scene0191_00: read frame 4300/5578
(process_with_single_worker pid=23811) scene0191_00: read frame 4400/5578
(process_with_single_worker pid=23811) scene0191_00: read frame 4500/5578
(process_with_single_worker pid=23811) scene0191_00: read frame 4600/5578
(process_with_single_worker pid=23811) scene0191_00: read frame 4700/5578
(process_with_single_worker pid=23811) scene0191_00: read frame 4800/5578
(process_with_single_worker pid=23811) scene0191_00: read frame 4900/5578
(process_with_single_worker pid=23811) scene0191_00: read frame 5000/5578
(process_with_single_worker pid=23811) scene0191_00: read frame 5100/5578
(process_with_single_worker pid=23811) scene0191_00: read frame 5200/5578
(process_with_single_worker pid=23811) scene0191_00: read frame 5300/5578
(process_with_single_worker pid=23811) scene0191_00: read frame 5400/5578
(process_with_single_worker pid=23811) scene0191_00: read frame 5500/5578
(process_with_single_worker pid=23811) Initializing voxel volume...
Traceback (most recent call last):
  File "/home/zxb/vortx/tools/generate_gt.py", line 489, in <module>
    results = ray.get(ray_worker_ids)
  File "/home/zxb/anaconda3/envs/vortx/lib/python3.9/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/home/zxb/anaconda3/envs/vortx/lib/python3.9/site-packages/ray/worker.py", line 1809, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(CompileError): ray::process_with_single_worker() (pid=23811, ip=172.31.151.121)
  File "/home/zxb/vortx/tools/generate_gt.py", line 434, in process_with_single_worker
    save_tsdf_full(args, scene, cam_intr, depth_all, cam_pose_all, color_all, save_mesh=False)
  File "/home/zxb/vortx/tools/generate_gt.py", line 285, in save_tsdf_full
    tsdf_vol_list.append(TSDFVolume(vol_bnds, voxel_size=args.voxel_size * 2 ** l, margin=args.margin))
  File "/home/zxb/vortx/vortx/tsdf_fusion.py", line 94, in __init__
    self._cuda_src_mod = SourceModule(
  File "/home/zxb/anaconda3/envs/vortx/lib/python3.9/site-packages/pycuda/compiler.py", line 349, in __init__
    cubin = compile(
  File "/home/zxb/anaconda3/envs/vortx/lib/python3.9/site-packages/pycuda/compiler.py", line 298, in compile
    return compile_plain(source, options, keep, nvcc, cache_dir, target)
  File "/home/zxb/anaconda3/envs/vortx/lib/python3.9/site-packages/pycuda/compiler.py", line 151, in compile_plain
    raise CompileError(
pycuda.driver.CompileError: nvcc compilation of /tmp/tmpuah84jjs/kernel.cu failed
[command: nvcc --cubin -arch sm_86 -I/home/zxb/anaconda3/envs/vortx/lib/python3.9/site-packages/pycuda/cuda kernel.cu]
[stderr:
nvcc fatal   : Value 'sm_86' is not defined for option 'gpu-architecture'

**Comment by leonelos-dev** [comment]
Why you closed this without a explanation?
