### ISSUE TITLE
Failing to format ScanNet for VoRTX

### ISSUE THREAD

**Issue by DevLeo1** [noahstier/vortx#4]
Hi, I want to pre-process the entire scannet dataset as you mention on README. 

```
python tools/preprocess_scannet.py --src path/to/scannet_src --dst path/to/new/scannet_dst
```

But it fails.

According to https://github.com/noahstier/vortx/blob/main/tools/preprocess_scannet.py, it says that it expects the following folder structure:

```
scannet_src/
    scannetv2_train.txt
    scannetv2_val.txt
    scannetv2_test.txt
    scans/
        scene_****_**/
            scene_****_**_vh_clean_2.ply
            color/
            depth/
            intrinsic/
            pose/
    scans_test/
        scene_****_**/
            scene_****_**_vh_clean_2.ply
            color/
            depth/
            intrinsic/
            pose/
```

However I don't have the following files:

- scannetv2_train.txt
- scannetv2_val.txt
- scannetv2_test.txt

This is the entire dataset I got:

![image](https://user-images.githubusercontent.com/116125432/198657182-d3774d6f-432b-41da-b57a-b3c11a96dba2.png)

As you can see I got scans and scans_tests, also another folder called tasks, but I don't have those txt files and that's the reason is throwing me errors.

Please can you help me? I really spent more than a month trying to run your project, and most of the time I'v been trying to download the entire dataset and I don't want to feel like I wasted so much time.

Thanks in advance!

**Comment by noahstier** [comment]
You can find those files here:

https://github.com/ScanNet/ScanNet/tree/master/Tasks/Benchmark

**Comment by DevLeo1** [comment]
> You can find those files here:
> 
> https://github.com/ScanNet/ScanNet/tree/master/Tasks/Benchmark

Awesome! Thank you!
