### ISSUE TITLE
Cannot format ScanNet for VoRTX

### ISSUE THREAD

**Issue by DevLeo1** [noahstier/vortx#6]
After downloading the whole dataset from Scannet and trying to run the following command to format the data:

`python tools/preprocess_scannet.py --src path/to/scannet_src --dst path/to/new/scannet_dst`

I'm getting some errors because I don't have the following folders inside each scan:

color/
depth/
intrinsic/
pose/

Here is a sample of how my scan folders looks like:

![image](https://user-images.githubusercontent.com/116125432/205561076-8ef78344-830e-459a-86fa-699f4cf3d5c0.png)

Do you know why I don't have those folders? I spent weeks downloading the whole dataset from Scannet and I'm stuck at this point.

Can you help me?

**Comment by DevLeo1** [comment]
Hi, can you help me? please. I'm stuck at this one, and I really need to test the code for a project

**Comment by noahstier** [comment]
Hi--the depth, color, pose, and intrinsics are contained in the .sens file. You can extract them using this code: https://github.com/ScanNet/ScanNet/tree/master/SensReader/python

**Comment by DevLeo1** [comment]
> Hi--the depth, color, pose, and intrinsics are contained in the .sens file. You can extract them using this code: https://github.com/ScanNet/ScanNet/tree/master/SensReader/python

Woah! Thank you very much! I'm going to test it and let you know

**Comment by DevLeo1** [comment]
> Hi--the depth, color, pose, and intrinsics are contained in the .sens file. You can extract them using this code: https://github.com/ScanNet/ScanNet/tree/master/SensReader/python

Indeed thank you very much for your help, I didn't know what to do until your response, I managed to generate those folders by running this command.

```
python reader.py --filename ../scans/scene0000_00/scene0000_00.sens --output_path ../test --export_depth_images --export_color_images --export_poses --export_intrinsics
```

Hope this helps someone else in the future.
